%CNN for MNIST  97.x%

testDigitData = imageDatastore('C:\Users\kongq\Desktop\machine_learning_ex\DataSet\MNIST\mnist_png\testing', ...
    'IncludeSubfolders',true,'LabelSource','foldernames');


trainDigitData = imageDatastore('C:\Users\kongq\Desktop\machine_learning_ex\DataSet\MNIST\mnist_png\training', ...
    'IncludeSubfolders',true,'LabelSource','foldernames');



layers = [imageInputLayer([28 28 1],...
            'DataAugmentation',{'none'},...
            'Normalization','none',...
            'Name','inputlayer');
    
          convolution2dLayer(5,6,...
                                'Stride',1,...
                                'Padding',[2,2],...
                                'NumChannels',1,...
                                'WeightLearnRateFactor',1,...
                                'BiasLearnRateFactor',1,...
                                'WeightL2Factor',1,...
                                'BiasL2Factor',2,...
                                'Name','C1');         
          reluLayer();
          maxPooling2dLayer(2,'Stride',2);
          
          
          
            convolution2dLayer(5,16,...
                        'Stride',1,...
                        'Padding',[2,2],...
                        'NumChannels',6,...
                        'WeightLearnRateFactor',1,...
                        'BiasLearnRateFactor',1,...
                        'WeightL2Factor',1,...
                        'BiasL2Factor',2,...
                        'Name','C1');         
          reluLayer();
          maxPooling2dLayer(2,'Stride',2);
          
          
          
          fullyConnectedLayer(10);
          softmaxLayer();
          classificationLayer()];
      
 options = trainingOptions('sgdm',...Environment
                            'CheckpointPath','',...
                            'ExecutionEnvironment','gpu',...
                            'InitialLearnRate',0.0001,...Learning Rate
                            'LearnRateSchedule','piecewise',...
                            'LearnRateDropPeriod',10,...
                            'LearnRateDropFactor',0.1,...
                            'L2Regularization',0.0005,...Regularization
                            'MaxEpochs',20,...Epochs
                            'MiniBatchSize',256,...Batch
                            'Momentum',0.8,...
                            'Shuffle','once',...       once|never
                            'Verbose',1,...             1  | 0             — Indicator to display the information on the training progress
                            'VerboseFrequency',100,...    50 | 0 
                            'OutputFcn',@plotTrainingAccuracy);


convnet = trainNetwork(trainDigitData,layers,options);


YPred = classify(convnet,testDigitData);
YTest = testDigitData.Labels;


accuracy = sum(YPred==YTest)/numel(YTest)